### ISSUE TITLE
`innerRef` is deprecated and will be removed in a future major version of Emotion, please use the `ref` prop instead 

### ISSUE THREAD

**Issue by AdnanDervisevic** [svenheden/react-formatted-number-input#3]
Seems a small refactoring is needed here to use the ref property instead of innerRef

**Comment by svenheden** [comment]
I've actually hold off on changing that as that would break the use with [Collector's `Input`](https://github.com/collector-bank/collector-portal-framework/tree/master/src/common/components/Input) as that component doesn't forward the ref to the DOM `<input />` element. Please fix that first, to avoid breaking things :)

**Comment by AdnanDervisevic** [comment]
Ah nice, will do

**Comment by AdnanDervisevic** [comment]
This has been changed in Portal Framework v18.0.0 which just released
